# .github/workflows/sync.yml
name: Snapshot Push to Other Repo

on:
  push:
    branches:
      - main

permissions:
  contents: write
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 1) マージ元リポジトリをフル履歴でチェックアウト
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: source

      # 2) マージ先リポジトリを target フォルダにチェックアウト
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: chilsonite/chilsonite-main
          token: ${{ secrets.SYNC_TOKEN }} # Fine‑grained token 必須
          ref: main
          path: target
          fetch-depth: 0

      # log用途としてファイル一覧を表示
      - name: List files
        run: |
          echo "---"
          echo "Source repo:"
              ls -R source
          echo "---"
          echo "Target repo:"
              ls -R target

        # 3) ターゲットのワークツリーを全消去（.git は保持）
      - name: Wipe target directory
        working-directory: target
        run: |
          # .git とその中身だけ残して他を削除
          find . -mindepth 1 \
            -not -path './.git' \
            -not -path './.git/*' \
            -delete

      - name: Sync files from source
        working-directory: target
        run: |
          # エラーで自動停止しないように
          set +e

          # source ディレクトリの中身だけを同期
          rsync -a --delete \
          --exclude='.git/' \
          --exclude='.github/workflows/sync.yml' \
          ../source/ .

          # rsync の終了コード取得
          rc=$?

          # 終了コード 24（部分転送エラー・警告）は成功とみなす
          if [ "$rc" -eq 24 ]; then
          rc=0
          fi

          # 最終ステップの終了コードを返す
          exit $rc

      # log用途としてファイル一覧を表示
      - name: List files 2
        run: |
          echo "---"
          echo "Source repo:"
              ls -R source
          echo "---"
          echo "Target repo:"
              ls -R target

      # 5) コミット＆プッシュ
      - name: Commit & push
        working-directory: target
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Sync snapshot from @${{ github.sha }}"
          git push origin HEAD:main --force
